### ISSUE TITLE
Automatically launch game feature and Tensokukan(天则观) compatibility.

### ISSUE THREAD

**Issue by Incubator85653** [evshiron/SokuMKII-nwjs#2]
你不能阅读英语,让我知道,有人将帮助翻译

These days Tensokukan(TSK or 天则观 in Chinese) are upgrading to International edition(2017 build 5).
We will provide official English, Chinese, and Japanese user experience.
There is a problem with publishing the TSK to our gamers.

When a user trying to launch the game, typically he will open "th123.exe" directly,
otherwise, the game will be launched by a third-party software tool.
TSK is just one of the third-party tool can be launch game quickly for users.
SokuMK2 is also provided such feature.

TSK save its data into an SQLite database, "Default.db".
And, TSK.exe find this database by a config file, "tsk.ini".

The old TSK(before 2016 build 1, vanilla 0.04) use a **full path** to record database location.
For example, 
```
[General]
Profile=C:\tsk\Default.db
``` 
New TSK(after 2016 build 1) use **relative path** find the database.
It looks like,
```
[General]
Profile=Default.db
```

Soon I noticed the user feedbacks.
The user who uses SokuMK2 to launched the game, TSK can not upload gaming data to the server.
I mean that SokuMK2 "Ask server and launch the game" button.
SokuMK2 display a file dialog to get the game binary before launched.

And in such situation, a user set the game exec to TSK's exec("tsk.exe"/"tsk_yamei.exe").
I found that SokuMK2 will launch the exec, using SokuMK2's working directory,
but not that exec's file location as the working directory. And so on, bugs emerged.
```
(In Linux platform you can often use "pwd" command to get the current working directory,
and most programs find DLLs or resources in working directory first.)
```

New TSK used relative path to create and read database, then if a user launched TSK by SokuMK2,
TSK will **create the database in SokuMK2's working directory** and write data to it.
After the game is closed, TSK data upload tool also **finds the database by relative path**.
This time it can not found the database anymore!
Because database in **stored in the SokuMK2 folder**.

Use relative path is a **design**, for Portable Edition in future updates.
People can "install" TSK on the USB drive and bring them to any place if they want.
For example, "网吧" in Chinese.

Could I ask you... update your code, don't make SokuMK2 affect exec's working directory?

**Comment by evshiron** [comment]
SokuMKII已经不会再更新了，而且也没有内置自动更新模块，推送起来很蛋疼。
不如来用Phantom吧。相信SokuMKII的用户已经收到过提示了。

关于工作目录的问题，其实是因为我创建子进程的时候没指定工作目录，所以「th123.exe」继承了父进程的工作目录。
理论上加两行代码就可以修复这个问题，但是不更新的理由上面已经说明了。

虽然我在GitHub上通常使用英文，但如果是国人，我是可以接受中文留言的。

**Comment by Incubator85653** [comment]
Therefor, TSK 2017 have to add more code to support such situation.

One thing left, how does SokuMK2 start process? If I create a shortcut for TSK,
will SokuMK2 execute shortcut directly? (Windows ".lnk" can specify exec working directory)
Or SokuMK2 convert it to ".exe"? If the user puts a text file, will notepad be launch?
And if that is a cmd script?

In python, GUI library "Tkinter" file dialog will return any file extension if the coder doesn't specify ".exe" only. Some process creates method support only ".exe", but there is also some method will open any file, just like a user double click on it.

What is the best in you think?

**Comment by evshiron** [comment]
`SokuMKII-nwjs` currently uses [spawn](https://nodejs.org/api/child_process.html#child_process_child_process_spawn_command_args_options) to create a child process, and as launching `.lnk` requires `{ 'shell': true }`, `SokuMKII-nwjs` should not be able to do it without a change.

**Comment by Incubator85653** [comment]
Created a cmd script called "tsk_SokuMKII.cmd".
```
@cd /d %~dp0
@start tsk_yamei
```

Seems SokuMK2 is able to execute this script.
